development:
  adapter: mysql2
  encoding: utf8
  database: starscream_dev
  pool: 5
  username: root
  password: skyl1n31
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: starscream_test
  pool: 5
  username: root
  password: skyl1n31
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: starscream_db
  pool: 5
  username: root
  password: skyl1n31
  socket: /var/run/mysqld/mysqld.sock
